import Client from "@/api/client";
import type { User } from "@/types";

export const retornarUsuario = async (id: number): Promise<User> => {
  try {
    if (!id) {
      throw new Error("ID do usu치rio n칚o fornecido");
    }
    const response = await Client.get(`/users/${id}`);
    if (!response.data || !response.data.usuario) {
      throw new Error("Usu치rio n칚o encontrado");
    }
    console.log("Usu치rio retornado:", response.data.usuario);
    return response.data.usuario;
  } catch (error: any) {
    throw new Error(`Erro ao buscar usu치rio: ${error.message}`);
  }
};
export const retornarUsuarios = async (empresaId: number): Promise<User[]> => {
  try {
    const response = await Client.get(`/enterprises/${empresaId}/users/`);
    if (!response || !response.data) {
      throw new Error("Empresa n칚o existe");
    }
    console.log("游닍 Resposta da API:", response.data);
    const usuarios = response.data.users || response.data;

    console.log(
      "游늶 Usuarios extra칤dos:",
      Array.isArray(usuarios) ? usuarios : [],
    );
    return Array.isArray(usuarios) ? usuarios : [];
  } catch (error) {
    throw new Error(`Failed to fetch users: ${error}`);
  }
};
export const deletarUsuario = async (id: number): Promise<void> => {
  try {
    if (!id) {
      throw new Error("ID do usu치rio n칚o fornecido");
    }
    const response = await Client.delete(`/users/${id}`);
    if (!response.data) {
      throw new Error("Usu치rio n칚o encontrado para deleta칞칚o");
    }
    return response.data;
  } catch (error: any) {
    throw new Error(`Erro ao deletar usu치rio: ${error.message}`);
  }
};
